#!/usr/bin/env python3
"""Regenerate harness wrapper files from skill/sdlc-contract.md.

CI runs `--check`; maintainers run `--write` after contract
amendments.

Generated files:
  AGENTS.md                                       (universal Layer-2)
  GEMINI.md                                       (Gemini CLI Layer-2)
  .cursor-plugin/rules/sdlc-contract.mdc           (Cursor alwaysApply rule)
  (Layer-1 configs — .claude/, .cursor-plugin/plugin.json, .claude-plugin/,
   gemini-extension.json — are NOT regenerated; they're structural.)

Exit codes:
  0  clean / wrote all
  1  drift detected (--check mode)
  2  config error
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _python_check import require_python_311  # noqa: E402

require_python_311()


def _read_contract_body(repo_root: Path) -> str:
    path = repo_root / "skill" / "sdlc-contract.md"
    text = path.read_text(encoding="utf-8")
    # Strip frontmatter if present
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end >= 0:
            text = text[end + 5:]
    return text.lstrip()


def _checksum(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]


ALL_TASK_TYPES = (
    '"phase-1-artifact-authoring", "phase-2-artifact-authoring", '
    '"phase-3-slice", "phase-3-refactor", "phase-4-test-authoring", '
    '"phase-4-test-execution", "phase-5-deploy-prep", '
    '"phase-5-release-cutting", "phase-6-CR-authoring", '
    '"phase-6-CR-implementation", "phase-6-incident-response", '
    '"phase-6-routine-maintenance"'
)

GENERATED_HEADER_AGENTS = f"""---
doc: AGENTS.md
status: signed
signed_by: Thanin Piromward on 2026-04-23
required_for: [{ALL_TASK_TYPES}]
cite_as: AGENT
---

<!--
  AGENTS.md — universal Layer-2 context file for non-hook harnesses.
  Auto-generated from skill/sdlc-contract.md by scripts/sync_wrappers.py.
  Do not edit this file directly; edit the canonical source and regenerate.
-->
"""

GENERATED_HEADER_GEMINI = f"""---
doc: GEMINI.md
status: signed
signed_by: Thanin Piromward on 2026-04-23
required_for: [{ALL_TASK_TYPES}]
cite_as: GEM
---

<!--
  GEMINI.md — Gemini CLI Layer-2 context file.
  Referenced from gemini-extension.json via `contextFileName`.
  Auto-generated from skill/sdlc-contract.md by scripts/sync_wrappers.py.
-->
"""

GENERATED_HEADER_CURSOR_MDC = """---
alwaysApply: true
description: SDLC strict-waterfall non-negotiable rules (Layer-2 supplement to the Cursor plugin hook)
---

<!-- Auto-generated from skill/sdlc-contract.md by scripts/sync_wrappers.py. -->
"""


def _build_agents(body: str) -> str:
    return GENERATED_HEADER_AGENTS + "\n" + body


def _build_gemini(body: str) -> str:
    return GENERATED_HEADER_GEMINI + "\n" + body


def _build_cursor_mdc(body: str) -> str:
    # Strip own frontmatter markers if body already has them; Cursor expects a
    # single top-level frontmatter block.
    return GENERATED_HEADER_CURSOR_MDC + "\n" + body


OUTPUTS = {
    Path("AGENTS.md"):                                      _build_agents,
    Path("GEMINI.md"):                                      _build_gemini,
    Path(".cursor-plugin/rules/sdlc-contract.mdc"):         _build_cursor_mdc,
}


def main(argv: list[str]) -> int:
    repo_root = Path(__file__).resolve().parent.parent
    mode = argv[1] if len(argv) > 1 else "--check"

    if mode not in ("--check", "--write"):
        print("usage: sync_wrappers.py [--check|--write]", file=sys.stderr)
        return 2

    body = _read_contract_body(repo_root)
    checksum = _checksum(body)
    print(f"contract body length={len(body)} sha12={checksum}")

    failures = 0
    for rel, builder in OUTPUTS.items():
        out_path = repo_root / rel
        expected = builder(body)

        if mode == "--write":
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(expected, encoding="utf-8")
            print(f"wrote {rel}")
            continue

        # --check: compare body only (ignore boilerplate differences that may
        # exist in hand-written wrappers for other content).
        if not out_path.exists():
            print(f"MISSING: {rel}")
            failures += 1
            continue

        actual = out_path.read_text(encoding="utf-8")
        # Normalize: check that the contract body appears in the wrapper.
        # Core rules 1-5 are the canonical content; confirm they're intact.
        for rule_id in ("1. REFUSE direct code edits",
                        "2. No code without a doc parent",
                        "3. No phase skipping",
                        "4. Signed docs are frozen",
                        "5. Reconciliation gate"):
            # Both "### 1. REFUSE..." and "1. **REFUSE..." variants accepted.
            pattern = re.escape(rule_id.split(".", 1)[1].strip()[:20])
            if not re.search(pattern, actual, re.IGNORECASE):
                print(f"DRIFT: {rel} missing rule content '{rule_id}'")
                failures += 1
                break
        else:
            print(f"ok {rel}")

    if failures:
        sys.stderr.write(f"\n{failures} wrapper(s) out of sync. Run: python3 scripts/sync_wrappers.py --write\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
